http:
  port: "8081"
  
log:
  Message: "Welcome to CI/CD Process with jenkins setup"
  
deployment:
  app:
    runtime: "4.6.1"
  region: "us-east-2"
  workers: "1"
  workerType: "MICRO"
#This is the config file.